mysite/bump/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit-game/$', views.submit_game, name='game_submit'),
    url(r'^rankings/$', views.rankings, name = 'rankings'),
    url(r'^rankings-sim/$', views.rankings_sim, name = 'rankings_sim'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^SGOAT/$', views.sgoat, name = 'sgoat'),
    url(r'login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profiles/(?P<player_identifier>[\w]+)/(?P<opponent_identifier>[\w]*)$', views.player_profile, name='profile'),
    url(r'^players/$', views.player_info, name='player_info'),
    url(r'^create-player/$', views.create_player, name='create_player'),
    url(r'^recent-submitted/$', views.recent_submitted_games, name='recent_submitted_games'),
    url(r'^edit-game/(?P<game_pk>[\d]+)/$', views.edit_game, name='edit_game'),
    url(r'^api/games$', views.api_games, name='api_games'),
    url(r'^api/games/(?P<player1>[\w]+)/(?P<player2>[\w]+)$', views.api_games_between, name='api_games_between'),
    url(r'^api/games/(?P<player>[\w]+)$', views.api_games_by, name='api_games_by'),
    url(r'^api/players$', views.api_players, name='api_players'),
    url(r'^balance',views.balance, name='balance'),


    
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('bump.urls', namespace="bump")),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/bump/forms.py
from django import forms
from .models import Player, Game
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime, timedelta, date


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ('identifier', 'first_name','last_name','duke','class_year','netid')
    def clean(self):
        cd = self.cleaned_data
        id = cd.get('identifier')
        if Player.objects.filter(identifier__iexact=id).exists():
            raise ValidationError('You tried to create a player with identifier '+id+', but that player already exists (case insensitive). Dingus!')
        return cd
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    player = forms.ModelChoiceField(queryset=Player.objects.order_by("identifier").filter(user=None))

    class Meta:
        model = User
        fields = ('username','email', 'password')

class GameEditForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('table','advantage','finisher')
    def clean(self):
        cd = self.cleaned_data
        ad = cd.get('advantage')
        fi = cd.get('finisher')
        if len(ad) > 0:
            if ad[0] == 'b':
                if fi == 'sweep':
                    raise ValidationError('You cannot sweep and break, dingus!')
        return cd
class BalanceForm(forms.Form):
    equation = forms.CharField(max_length = 200)
    def clean(self):
        return self.cleaned_data
class RankingsSimulationForm(forms.Form):
    start_date = forms.SplitDateTimeField(input_time_formats=['%I:%M%p'], input_date_formats=['%m/%d/%y'],required=False,widget=forms.SplitDateTimeWidget(date_format='%m/%d/%y',time_format='%I:%M%p'),initial=datetime(2014, 8, 24, 0, 0))
    end_date = forms.SplitDateTimeField(input_time_formats=['%I:%M%p'], input_date_formats=['%m/%d/%y'],required=False,widget=forms.SplitDateTimeWidget(date_format='%m/%d/%y',time_format='%I:%M%p'),initial=datetime(2016, 12, 31, 17, 0))
    brunswick_table = forms.BooleanField(initial=True,required=False)
    will_table = forms.BooleanField(initial=True,required=False)
    kaighn_table = forms.BooleanField(initial=True,required=False)
    adil_table = forms.BooleanField(initial=True,required=False)
    loop_table = forms.BooleanField(initial=True,required=False)
    rectangle_table = forms.BooleanField(required=False)
    active_players_only = forms.BooleanField(required=False)
class GameSubmissionForm(forms.Form):
    date = forms.DateTimeField(widget=forms.SplitDateTimeWidget, required=False)
    table = forms.ChoiceField(choices=Game.table_choices_tuples)
    game_text = forms.CharField(widget=forms.Textarea)
    
    def clean(self):
        cd = self.cleaned_data
        text = cd.get('game_text')
        date = cd.get('date')
        if date is None:
            cd['date'] = timezone.now()
        if text is None:
            raise ValidationError('You\'ve entered nothing. Dingus!')
        games = [s.strip() for s in text.splitlines()]
        for game in games:
            gt = game.split()
            if len(gt) < 2:
                raise ValidationError("You need to specify a winner and loser.")
            winner = gt[0]
            if not Player.objects.filter(identifier__iexact=winner).exists():
                raise ValidationError(winner + " is not a registered player.")
            try:
                num_games = int(gt[1])
                if num_games < 1:
                    raise ValidationError("Please enter a positive number of games. Not "+str(num_games))
                if num_games > 5:
                    raise ValidationError("You can only enter 5 games, dingus. Not "+str(num_games))
                loser = gt[2]
                cut_index = 3
            except ValueError:
                loser = gt[1]
                cut_index = 2
            if not Player.objects.filter(identifier__iexact=loser).exists():
                raise ValidationError(loser+" is not a registered player.")
            if winner == loser:
                raise ValidationError(winner + " cannot beat themself, silly.")
            tags = gt[cut_index:]
            finisher_selected = False
            advantage_selected = False
            bbreak = False
            sweep = False
            for tag in tags:
                if tag in Game.advantage_choices:
                    if tag[0] == 'b':
                        bbreak = True
                    if advantage_selected:
                        raise ValidationError(tag + " is the second advantage codeword in a line. You can only have one.")
                    advantage_selected = True
                elif tag in Game.finisher_choices:
                    if tag == 'sweep':
                        sweep = True
                    if finisher_selected:
                        raise ValidationError(tag + " is the second finisher codeword in a line. You can only have one.")
                    finisher_selected = True
                else:
                    raise ValidationError(tag+" is not a valid word.")
            if bbreak and sweep:
                raise ValidationError('It\'s impossible to break AND sweep, ya dingus.')
                
            
        return cd
        
        
        

mysite/bump/views.py
from django.shortcuts import render, get_object_or_404
from .models import Player, Game
import math
from .forms import GameSubmissionForm, UserForm, PlayerForm, GameEditForm, RankingsSimulationForm, BalanceForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import datetime, timedelta, date
from django.utils import timezone
from django.core import serializers
from django.db.models import Q
from django.contrib.auth import logout
from .elo import eloRecords, SgoatCalculator
import elo
import operator
import sympy

class Compound(object):
    def __init__(self,atoms):
        self.atoms = atoms
        self.coefficient = -1
    def __str__(self):
        ret = str(self.coefficient) if self.coefficient != 1 else ""
        for at in self.atoms:
            ret+= at.__str__()
        return ret
    def atom_amount(self,name):
        total = 0
        for atom in self.atoms:
            if atom.name == name:
                total += atom.subscript
        return total
class Atom(object):
    def __init__(self,str,subscript):
        self.name = str
        self.subscript = subscript
    def __str__(self):
        sub = "<sub>"+str(self.subscript)+"</sub>" if self.subscript != 1 else ""
        return self.name+sub
class Equation(object):
    def __init__(self,reactants,products):
        self.reactants = reactants
        self.products = products
    def __str__(self):
        ret = ""
        ret+= "+".join(map(str,self.reactants))
        ret+= " -> "
        ret+= "+".join(map(str,self.products))
        return ret
    def atoms(self,products=False):
        side = self.products if products else self.reactants
        ret = []
        for compound in side:
            for atom in compound.atoms:
                ret.append(atom.name)
        return set(ret)
    def num_coefficients(self):
        return len(self.reactants)+len(self.products)
    def assign_coefficient(self,index,coefficient):
        if index >= len(self.reactants):
            self.products[index-len(self.reactants)].coefficient = coefficient
        else:
            self.reactants[index].coefficient = coefficient
def parse_side(reactants_list):
    ret = []
    for compound in reactants_list:
        compound = compound.strip()
        atoms = []
        cur_element = ""
        cur_subscript = ""
        for i in range(len(compound)):
            reinit = None
            cut = False
            if i == len(compound)-1:
                cut = True
            char = compound[i]
            if char.isdigit():
                if cur_element == "":
                    raise ValueError("test")
                cur_subscript += char
                cut = i == len(compound)-1 or not compound[i+1].isdigit()
            elif char.isalpha():
                if cur_element=="":
                    if char.isupper():
                        cur_element += char
                    else:
                        raise ValueError("test")
                else:
                    if char.isupper():
                        cut = True
                        reinit = char
                    else:
                        cur_element += char
            else:
                raise ValueError("test")
            if cut:
                subscript = 1 if cur_subscript=="" else int(cur_subscript)
                atom = Atom(cur_element,subscript)
                atoms.append(atom)
                cur_element="" if reinit == None else reinit
                cur_subscript=""
                if i==len(compound)-1 and reinit != None:
                    subscript = 1 if cur_subscript=="" else int(cur_subscript)
                    atom = Atom(cur_element,subscript)
                    atoms.append(atom)
                    cur_element="" if reinit == None else reinit
                    cur_subscript=""
        ret.append(Compound(atoms))
    return ret
def parse_equation(eqn):
    split = eqn.split("->")
    reactants_str = split[0].split("+")
    products_str = split[1].split("+")
    reactants = parse_side(reactants_str)
    products = parse_side(products_str)
    equation = Equation(reactants,products)
    return equation
def balance_equation(eqn):
    atoms = eqn.atoms()
    prod_atoms = eqn.atoms(products=True)
    print atoms
    print prod_atoms
    for atom in prod_atoms:
        if atom not in atoms:
            return False,"The atom "+atom+" appears on the products but not the reactants side. Dingus."
    for atom in atoms:
        if atom not in prod_atoms:
            return False,"The atom "+atom+" appears on the reactants but not the products side. Dingus."
    matrix = []
    for atom in atoms:
        row = []
        for compound in eqn.reactants:
            row.append(compound.atom_amount(atom))
        for compound in eqn.products:
            row.append(-1*compound.atom_amount(atom))
        row.append(0)
        matrix.append(row)
    matrix = [tuple(row) for row in matrix]
    matrix = tuple(matrix)
    matrix = sympy.Matrix(matrix)
    symbols = sympy.symbols("a0:"+str(eqn.num_coefficients()))
    soln = sympy.solve_linear_system(matrix,*symbols)
    print soln
    if any(map(lambda x : x == sympy.sympify(0), soln.values())):
        return False,"This equation has no solution. Dingus."
    
    if len(soln) < len(symbols)-1:
        return False,"This equation is not balanceable, as there are multiple correct answers. Dingus."
    def soln_copy():
        return {k:v for k,v in soln.items()}
    i = 0
    def condition(solution):
        if solution == None:
            return True
        for k,v in solution.items():
            if not v.is_integer:
                return True
        return False
    final_solution = None
    free_symbol = symbols[-1]
    
    increment = 1
    fractions = []
    for k,v in soln.items():
        for arg in v.args:
            if arg.is_real:
                fractions.append(sympy.fraction(arg)[1])
                break
    if len(fractions) > 0:
        increment = reduce(sympy.lcm,fractions)
    
    while condition(final_solution):
        i+=increment
        copy = soln_copy()
        for k,v in copy.items():
            copy[k] = v.subs(free_symbol,i)
        final_solution = copy
    final_solution[free_symbol] = i
    for k,v in final_solution.items():
        eqn.assign_coefficient(symbols.index(k),v)
    return True,""


def balance(request):
    if request.method == 'POST':
        form = BalanceForm(request.POST)
        if form.is_valid():
            equation = form.cleaned_data.get("equation")
            try:
                eqn = parse_equation(equation)
                balanced,msg = balance_equation(eqn)
            except:
                return HttpResponse("Your equation was nonsensical. Remember -> must appear at least once in every valid equation. Read the rules. Also, I don't yet support parentheses so (SO2)2 doesn't work, so write it as S2O4. Sorrrrrry!")
            if not balanced:
                return HttpResponse(msg)
            return HttpResponse(str(eqn))

    else:
        form = BalanceForm()
    
    return render(request, 'bump/balance.html', {'form': form})
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

def api_games(request):
    data = serializers.serialize("json", Game.objects.all())
    return HttpResponse(data, content_type='application/json')
def api_games_by(request, player):
    data = serializers.serialize("json", Game.objects.filter(Q(winner__identifier=player) | Q(loser__identifier=player)))
    return HttpResponse(data, content_type='application/json')
def api_games_between(request, player1, player2):
    players = [player1, player2]
    data = serializers.serialize("json", Game.objects.filter(winner__identifier__in=players, loser__identifier__in=players))
    return HttpResponse(data, content_type='application/json')
def api_players(request):
    data = serializers.serialize("json", Player.objects.all())
    return HttpResponse(data, content_type='application/json')
def index(request):
    ordered_games = Game.objects.order_by('-date','-pk')
    feed_games = ordered_games[:20]
    now = timezone.now()
    month_games = ordered_games.filter(date__gte = (now - timedelta(days = 30)))
    week_games = month_games.filter(date__gte = (now - timedelta(days = 7)))
    day_games = week_games.filter(date__gte = (now - timedelta(days=1)))
    hour_games = day_games.filter(date__gte = (now - timedelta(hours=1)))
    start_date = datetime.combine(timezone.localtime(timezone.now()-timedelta(hours=6)).date(),datetime.min.time()) + timedelta(hours=6)
    end_date = start_date + timedelta( days=1 ) 
    games_today = Game.objects.filter(date__range=(start_date, end_date))
    def tupleify(playerA, playerB):
        if playerA < playerB:
            return (playerA,playerB),True
        else:
            return (playerB,playerA),False
    series_dict = {}
    for game in games_today:
        tuple,first_player_won = tupleify(game.winner.identifier,game.loser.identifier)
        if tuple not in series_dict.keys():
            series_dict[tuple] = [0,0]
        if first_player_won:
            series_dict[tuple][0]+=1
        else:
            series_dict[tuple][1]+=1
    series_tuples = sorted(series_dict.items(), key=lambda e: -e[1][0]-e[1][1])
    series_tuples = [x for x in series_tuples if x[1][0]+x[1][1] >= 2]
    context = {
        'month_count' : month_games.count(),
        'week_count' : week_games.count(),
        'day_count' : day_games.count(),
        'hour_count' : hour_games.count(),
        'player_count' : Player.objects.all().count(),
        'player_week' : Player.objects.filter(start_date__gte = (now - timedelta(days=7))).count(),
        'games_feed' : feed_games,

mysite/bump/templates/bump/achievements.html
{% extends 'bump/base.html' %}
{% block content %}    
    <h4>Achievements</h4>
    {% if achievement_tuples %}
    <ul>
    {% for ach,count in achievement_tuples %}
        <li>{{ach.name}}: {{ach.description}} ({{ach.points}} points) - {{count}} people have achieved it</li>
    {% endfor %}
    </ul>
    {% endif %}
    
{% endblock %}

mysite/bump/templates/bump/balance.html
{% extends 'bump/base.html' %}

{% block content %}
<form action="/balance/" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
<h4>How To Use</h4>
<p>Enter an equation into the text box. An equation looks something like H2 + O2 -> H20.
Every equation has one "->". An element, like "H" or "Fl", must start with a capital letter 
and encompasses all following lowercase characters. The subscript is put after the atom. You
can write something like water as "H2O" or "H2O1", if assumes a subscript of 1 if left out.</p>
<h4>Some Examples (Copy and paste them, or modify them if you'd like)</h4>
<ul>
<li>CH4 + O2 -> CO2 + H2</li>
<li>HIO3 + FeI2 + HCl -> FeCl3 + ICl + H2O</li>
<li>Hello + Hiya3 -> Hello4Hiya6 (valid elements according to our rules)</li>
<li>Cr4N48H96C24O24Cr3C18N18+ KMnO4 + H2SO4 -> K2Cr2O7 + MnSO4 + CO2 + KNO3 + K2SO4 + HOH (The Mother of All Chem Equations)</li>
</ul>
<h4>Bad Examples</h4>
<ul>
<li>e2 + H -> e4H2 (e is not a valid element)</li>
<li>O2 + H -> O2 (H does not appear on right hand side)</li>
<li>O2 + H -> O2 + H (this equation has no answer, because there are multiple ways to balance)</li>
<li>OH + HC -> OHC (this equation has no solution whatsoever, apart from the trivial solution where all coefficients are zero)</ul>
<h5>Why?</h5>
<p>This is the final paper/project for Dr. Baldwin's Chem 91, by Kaighn Kevlin.
{% endblock %}

mysite/bump/templates/bump/base.html
<!-- Base html template for entire site. Contains links to bootstrap CSS -->

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- {% load staticfiles %} -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <title>{% block title %}Bump Site{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="#">BumpWorks</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      <!-- index should be renamed to feed -->

      <li><a href="{% url 'bump:index' %}">Game Feed</a></li>
        <li><a href="{% url 'bump:game_submit' %}">Submit Game</a></li>
        <li><a href="{% url 'bump:rankings' %}">Rankings</a></li>
        <li><a href="{% url 'bump:player_info' %}">Players</a></li>
        <li><a href="{% url 'bump:create_player' %}">Create Player</a></li> 
        <li><a href="http://bump.suyashkumar.com">Bump Explore</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li>Hello, {{ user.username }}!</li>
      <li><a href="{% url 'bump:profile' user.player '' %}">My Profile</a></li>
      <li><a href="{% url 'bump:logout' %}">Log out</a></li>
      {% else %}
      <li><a href="{% url 'bump:login' %}">Log in</a></li>
      <li><a href="{% url 'bump:register' %}">Register</a></li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

mysite/bump/templates/bump/edit_game.html
{% extends 'bump/base.html' %}
{% block content %}
    <h1>Edit Game</h1>
    <form id="game_edit_form" method="post" action="/edit-game/{{game.pk}}/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit Edit" />
    </form>


{% endblock %}

mysite/bump/templates/bump/feed.html
{% extends 'bump/base.html' %}
{% block content %}    
    <h5>{{hour_count}} games past hour, {{day_count}} past 24 hours, {{week_count}} past 7 days, {{month_count}} past 30 days</h5>
    <h5>{{player_count}} players have bumped, {{player_week}} new players in the past 7 days</h5>
    {% if games_feed %}
    <ul>
    {% for game in games_feed %}
        <li>{{ game.date }} {{ game }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% if series_tuples %}
    <h5>Top Series for Today</h5>
    <ol>
    {% for series in series_tuples %}
        {% if series.1.0 >= series.1.1 %}
        <li>{{ series.0.0 }} {{series.1.0}}-{{series.1.1}} {{series.0.1}}</li>
        {% else %}
        <li>{{ series.0.1 }} {{series.1.1}}-{{series.1.0}} {{series.0.0}}</li>
        {% endif %}
    {% endfor %}
    </ol>
    {% endif %}
    
{% endblock %}

mysite/bump/templates/bump/game_submit.html
{% extends 'bump/base.html' %}

{% block content %}
<body onload='setFocusToBox()'>
<form action="/submit-game/" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% if feed %}
    <ul>
    {% for game in feed %}
        <li>{{ game.date }} {{ game}}</li>
    {% endfor %}
    </ul>
{% endif %}
<a href='/recent-submitted/'>Edit your recently submitted games.</a>
</body>


<script type="text/javascript">
     function setFocusToBox(){
        document.getElementById("id_game_text").focus();
     }
</script>

{% endblock %}

mysite/bump/templates/bump/login.html
{% extends 'bump/base.html' %}
{% block content %}
        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>
{% endblock %}

mysite/bump/templates/bump/players.html
{% extends 'bump/base.html' %}
{% block content %}
    {% if players %}
    <table class="table table-striped table-condensed table-hover">
      <thead>
        <tr>
            <th>Identifier</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Duke</th>
            <th>Class</th>
            <th>Registered</th>
        </tr>
      </thead>
      <tbody>  
    {% for p in players %}
        <tr>
            <td>{{p.identifier}}</td>
            <td>{{p.first_name}}</td>
            <td>{{p.last_name}}</td>
            <td>{%if p.duke%} X {% endif %}</td>
            <td>{{p.class_year}}</td>
            <td>{%if p.user%} X {% endif %}</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>
    {% endif %}
{% endblock %}

mysite/bump/templates/bump/rankings.html
{% extends 'bump/base.html' %}
{% block content %}
    {% if players %}
    <p><i>Rankings are updated Fridays at 5pm.</i></p>
    <br/>
    <ol>
    {% for player in players %}
        <li>{{ player.identifier }} {{ player.elo }} ({{player.wins}}-{{player.losses}})</li>
    {% endfor %}
    </ol>
    {% endif %}
    {% if on_the_bump %}
    <h4>On the bump!</h4>
    <ol>
    {% for player in on_the_bump %}
        <li>{{ player.identifier }} ({{player.wins}}-{{player.losses}})</li>
    {% endfor %}
    </ol>
    {% endif %}
{% endblock %}

mysite/bump/templates/bump/rankings_sim.html
{% extends 'bump/base.html' %}
{% block content %}
    {% if form %}
    <form id="rankings_form" method="post" action="/rankings-sim/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Run" />
    </form>
    {% endif %}
    {% if player_elo_tuples %}
    <ol>
    {% for tuple in player_elo_tuples %}
        <li>{{tuple.0}}: {{tuple.1}} ({{tuple.2}}-{{tuple.3}})</li>
    {% endfor %}
    </ol>
    {% endif %}
{% endblock %}

mysite/bump/templates/bump/recent_submitted.html
{% extends 'bump/base.html' %}
{% block content %}    
    <h4>Games you have submitted in the past 20 minutes:</h4>
    {% if recent_submitted_games %}
    <ul>
    {% for game in recent_submitted_games %}
        <li><a href='/edit-game/{{ game.pk }}'>{{ game.date }} {{ game }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
    
{% endblock %}

mysite/bump/templates/bump/register.html
{% extends 'bump/base.html' %}
{% block content %}
        {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="/">Return to the homepage.</a><br />
        {% else %}
        
        <h3>Register with Le Bump</h3>      
        
        <strong>**Check the </strong>
        <a href="/players/">list of players</a>
        <strong> to find your "Player" identifier**</strong><br />
        <br>
        
        <form id="user_form" method="post" action="/register/">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}

mysite/bump/templates/bump/sgoat.html
{% extends 'bump/base.html' %}
{% block content %}
    <p><i>Number of weeks spent at world #2. SGOAT status is updated Fridays at 5pm.</i></p>
    <br/>
    <ol>
    {% for player,place_count in placeDict %}
        <li>{{ player.identifier }}: {{place_count}}</li>
    {% endfor %}
    <h5>Records Against</h5>
    {% for player,opponent_tuples in records_against %}
        <p>{{player.identifier}} Against:</p>
        <ul>
        {% for opponent,wins,loses in opponent_tuples  %}
        <li>{{opponent.identifier}}: ({{wins}}-{{loses}})</li>
        {% endfor %}
        </ul>
    {% endfor %}
    <h5>Overall Record + (Non-Tyler Win % on Brunswick)</h5>
    <ul>
    {% for player,tup in nontyler_record %}
        <li>{{ player.identifier }} ({{player.wins}}-{{player.losses}}) | {{tup.0|floatformat:3}} ({{tup.1}}-{{tup.2}})</li>
    {% endfor %}
    </ul>
{% endblock %}